<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="PerceptronWrapper">
      <HintPath>..\PerceptronWrapper\x64\Release\PerceptronWrapper.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
